/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as NewRouteImport } from './routes/new'
import { Route as OIdRouteImport } from './routes/o.$id'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as ResultsSlugRouteImport } from './routes/results.$slug'
import { Route as ShareSlugRouteImport } from './routes/share.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OIdRoute = OIdRouteImport.update({
  id: '/o/$id',
  path: '/o/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsSlugRoute = ResultsSlugRouteImport.update({
  id: '/results/$slug',
  path: '/results/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareSlugRoute = ShareSlugRouteImport.update({
  id: '/share/$slug',
  path: '/share/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/new': typeof NewRoute
  '/o/$id': typeof OIdRoute
  '/p/$slug': typeof PSlugRoute
  '/results/$slug': typeof ResultsSlugRoute
  '/share/$slug': typeof ShareSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/new': typeof NewRoute
  '/o/$id': typeof OIdRoute
  '/p/$slug': typeof PSlugRoute
  '/results/$slug': typeof ResultsSlugRoute
  '/share/$slug': typeof ShareSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/new': typeof NewRoute
  '/o/$id': typeof OIdRoute
  '/p/$slug': typeof PSlugRoute
  '/results/$slug': typeof ResultsSlugRoute
  '/share/$slug': typeof ShareSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/new'
    | '/o/$id'
    | '/p/$slug'
    | '/results/$slug'
    | '/share/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/new'
    | '/o/$id'
    | '/p/$slug'
    | '/results/$slug'
    | '/share/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/new'
    | '/o/$id'
    | '/p/$slug'
    | '/results/$slug'
    | '/share/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  NewRoute: typeof NewRoute
  OIdRoute: typeof OIdRoute
  PSlugRoute: typeof PSlugRoute
  ResultsSlugRoute: typeof ResultsSlugRoute
  ShareSlugRoute: typeof ShareSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$id': {
      id: '/o/$id'
      path: '/o/$id'
      fullPath: '/o/$id'
      preLoaderRoute: typeof OIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$slug': {
      id: '/results/$slug'
      path: '/results/$slug'
      fullPath: '/results/$slug'
      preLoaderRoute: typeof ResultsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$slug': {
      id: '/share/$slug'
      path: '/share/$slug'
      fullPath: '/share/$slug'
      preLoaderRoute: typeof ShareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  NewRoute: NewRoute,
  OIdRoute: OIdRoute,
  PSlugRoute: PSlugRoute,
  ResultsSlugRoute: ResultsSlugRoute,
  ShareSlugRoute: ShareSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
