/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AvailabilityRouteImport } from './routes/availability'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as HomeRouteImport } from './routes/home'
import { Route as NewRouteImport } from './routes/new'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SessionZeroRouteImport } from './routes/session-zero'
import { Route as TestRouteImport } from './routes/test'
import { Route as DSlugRouteImport } from './routes/d.$slug'
import { Route as GSlugRouteImport } from './routes/g.$slug'
import { Route as OIdRouteImport } from './routes/o.$id'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as ResultsSlugRouteImport } from './routes/results.$slug'
import { Route as ShareSlugRouteImport } from './routes/share.$slug'
import { Route as ApiPublicHooksDriftAlarmRouteImport } from './routes/api/public/hooks/drift-alarm'
import { Route as ApiPublicHooksNudgeDeadlinesRouteImport } from './routes/api/public/hooks/nudge-deadlines'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityRoute = AvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionZeroRoute = SessionZeroRouteImport.update({
  id: '/session-zero',
  path: '/session-zero',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const DSlugRoute = DSlugRouteImport.update({
  id: '/d/$slug',
  path: '/d/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GSlugRoute = GSlugRouteImport.update({
  id: '/g/$slug',
  path: '/g/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OIdRoute = OIdRouteImport.update({
  id: '/o/$id',
  path: '/o/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsSlugRoute = ResultsSlugRouteImport.update({
  id: '/results/$slug',
  path: '/results/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareSlugRoute = ShareSlugRouteImport.update({
  id: '/share/$slug',
  path: '/share/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDriftAlarmRoute =
  ApiPublicHooksDriftAlarmRouteImport.update({
    id: '/api/public/hooks/drift-alarm',
    path: '/api/public/hooks/drift-alarm',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksNudgeDeadlinesRoute =
  ApiPublicHooksNudgeDeadlinesRouteImport.update({
    id: '/api/public/hooks/nudge-deadlines',
    path: '/api/public/hooks/nudge-deadlines',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/availability': typeof AvailabilityRoute
  '/groups': typeof GroupsRoute
  '/home': typeof HomeRoute
  '/new': typeof NewRoute
  '/reset-password': typeof ResetPasswordRoute
  '/session-zero': typeof SessionZeroRoute
  '/test': typeof TestRoute
  '/d/$slug': typeof DSlugRoute
  '/g/$slug': typeof GSlugRoute
  '/o/$id': typeof OIdRoute
  '/p/$slug': typeof PSlugRoute
  '/results/$slug': typeof ResultsSlugRoute
  '/share/$slug': typeof ShareSlugRoute
  '/api/public/hooks/drift-alarm': typeof ApiPublicHooksDriftAlarmRoute
  '/api/public/hooks/nudge-deadlines': typeof ApiPublicHooksNudgeDeadlinesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/availability': typeof AvailabilityRoute
  '/groups': typeof GroupsRoute
  '/home': typeof HomeRoute
  '/new': typeof NewRoute
  '/reset-password': typeof ResetPasswordRoute
  '/session-zero': typeof SessionZeroRoute
  '/test': typeof TestRoute
  '/d/$slug': typeof DSlugRoute
  '/g/$slug': typeof GSlugRoute
  '/o/$id': typeof OIdRoute
  '/p/$slug': typeof PSlugRoute
  '/results/$slug': typeof ResultsSlugRoute
  '/share/$slug': typeof ShareSlugRoute
  '/api/public/hooks/drift-alarm': typeof ApiPublicHooksDriftAlarmRoute
  '/api/public/hooks/nudge-deadlines': typeof ApiPublicHooksNudgeDeadlinesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/availability': typeof AvailabilityRoute
  '/groups': typeof GroupsRoute
  '/home': typeof HomeRoute
  '/new': typeof NewRoute
  '/reset-password': typeof ResetPasswordRoute
  '/session-zero': typeof SessionZeroRoute
  '/test': typeof TestRoute
  '/d/$slug': typeof DSlugRoute
  '/g/$slug': typeof GSlugRoute
  '/o/$id': typeof OIdRoute
  '/p/$slug': typeof PSlugRoute
  '/results/$slug': typeof ResultsSlugRoute
  '/share/$slug': typeof ShareSlugRoute
  '/api/public/hooks/drift-alarm': typeof ApiPublicHooksDriftAlarmRoute
  '/api/public/hooks/nudge-deadlines': typeof ApiPublicHooksNudgeDeadlinesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/availability'
    | '/groups'
    | '/home'
    | '/new'
    | '/reset-password'
    | '/session-zero'
    | '/test'
    | '/d/$slug'
    | '/g/$slug'
    | '/o/$id'
    | '/p/$slug'
    | '/results/$slug'
    | '/share/$slug'
    | '/api/public/hooks/drift-alarm'
    | '/api/public/hooks/nudge-deadlines'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/availability'
    | '/groups'
    | '/home'
    | '/new'
    | '/reset-password'
    | '/session-zero'
    | '/test'
    | '/d/$slug'
    | '/g/$slug'
    | '/o/$id'
    | '/p/$slug'
    | '/results/$slug'
    | '/share/$slug'
    | '/api/public/hooks/drift-alarm'
    | '/api/public/hooks/nudge-deadlines'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/availability'
    | '/groups'
    | '/home'
    | '/new'
    | '/reset-password'
    | '/session-zero'
    | '/test'
    | '/d/$slug'
    | '/g/$slug'
    | '/o/$id'
    | '/p/$slug'
    | '/results/$slug'
    | '/share/$slug'
    | '/api/public/hooks/drift-alarm'
    | '/api/public/hooks/nudge-deadlines'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AvailabilityRoute: typeof AvailabilityRoute
  GroupsRoute: typeof GroupsRoute
  HomeRoute: typeof HomeRoute
  NewRoute: typeof NewRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SessionZeroRoute: typeof SessionZeroRoute
  TestRoute: typeof TestRoute
  DSlugRoute: typeof DSlugRoute
  GSlugRoute: typeof GSlugRoute
  OIdRoute: typeof OIdRoute
  PSlugRoute: typeof PSlugRoute
  ResultsSlugRoute: typeof ResultsSlugRoute
  ShareSlugRoute: typeof ShareSlugRoute
  ApiPublicHooksDriftAlarmRoute: typeof ApiPublicHooksDriftAlarmRoute
  ApiPublicHooksNudgeDeadlinesRoute: typeof ApiPublicHooksNudgeDeadlinesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability': {
      id: '/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-zero': {
      id: '/session-zero'
      path: '/session-zero'
      fullPath: '/session-zero'
      preLoaderRoute: typeof SessionZeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$slug': {
      id: '/d/$slug'
      path: '/d/$slug'
      fullPath: '/d/$slug'
      preLoaderRoute: typeof DSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$slug': {
      id: '/g/$slug'
      path: '/g/$slug'
      fullPath: '/g/$slug'
      preLoaderRoute: typeof GSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$id': {
      id: '/o/$id'
      path: '/o/$id'
      fullPath: '/o/$id'
      preLoaderRoute: typeof OIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$slug': {
      id: '/results/$slug'
      path: '/results/$slug'
      fullPath: '/results/$slug'
      preLoaderRoute: typeof ResultsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$slug': {
      id: '/share/$slug'
      path: '/share/$slug'
      fullPath: '/share/$slug'
      preLoaderRoute: typeof ShareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/drift-alarm': {
      id: '/api/public/hooks/drift-alarm'
      path: '/api/public/hooks/drift-alarm'
      fullPath: '/api/public/hooks/drift-alarm'
      preLoaderRoute: typeof ApiPublicHooksDriftAlarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/nudge-deadlines': {
      id: '/api/public/hooks/nudge-deadlines'
      path: '/api/public/hooks/nudge-deadlines'
      fullPath: '/api/public/hooks/nudge-deadlines'
      preLoaderRoute: typeof ApiPublicHooksNudgeDeadlinesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AvailabilityRoute: AvailabilityRoute,
  GroupsRoute: GroupsRoute,
  HomeRoute: HomeRoute,
  NewRoute: NewRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SessionZeroRoute: SessionZeroRoute,
  TestRoute: TestRoute,
  DSlugRoute: DSlugRoute,
  GSlugRoute: GSlugRoute,
  OIdRoute: OIdRoute,
  PSlugRoute: PSlugRoute,
  ResultsSlugRoute: ResultsSlugRoute,
  ShareSlugRoute: ShareSlugRoute,
  ApiPublicHooksDriftAlarmRoute: ApiPublicHooksDriftAlarmRoute,
  ApiPublicHooksNudgeDeadlinesRoute: ApiPublicHooksNudgeDeadlinesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
